### ISSUE TITLE
Bonjour, est-il possible de discuter avec l'auteur ? 

### ISSUE THREAD

**Issue by etienneleba** [democratie-2-0/GPI#1]

**Comment by democratie-2-0** [comment]
Bonjour Etienne, bien entendu ! c'est mon souhait : discuter, échanger, construire, améliorer

**Comment by etienneleba** [comment]
Parfait ! J'avais un doute si le compte était toujours actif. Je m'intéresse aux enjeux monétaires et démocratiques depuis quelques années et en voulant mettre mes idées sur papier, et sur git pour profiter du versionning, je me suis demandé si quelqu'un n'avait pas eu la même idée de mettre ses idées sur github. C'est comme ça que je suis tombé sur votre repo. 
Êtes-vous un collectif ou une personne indépendante ? Est-il possible de parler par mail ?

**Comment by democratie-2-0** [comment]
Peu importe le ou les auteurs, moins la notion d'auteur sera visible, plus facile sera l'appropriation de ces idées par le plus grand nombre. Pourquoi discuter par mail, ne le faisons-nous pas déjà ici ?

**Comment by etienneleba** [comment]
J'utilise github pour des tâches professionnelles, si nous échangeons sur ce sujet complexe de la démocratie participative, je vais être amené à enoncer mes idées de manière non structuré et cela me dérange de le faire sur cette plate-forme qui n'est pas faite pour ça. Je suis dans la même situation que vous en fait.

**Comment by democratie-2-0** [comment]
nous énonçons déjà ici des idées de manière non structurée à propos du mode de communication et manifestement ça ne pose pas de problème. Pour ma part je souhaite conserver tous les échanges visibles de tous afin que chacun puisse en prendre connaissance et compléter les discussions, d'autant plus que vous pouvez modifier et même supprimer vos billets si vous changez d'avis. Il me semble donc plus adapté de continuer nos échanges ici plutôt que sur un autre site ou par email. Si vous souhaitez ne pas mélanger vos activités professionnelles et personnelles, il vous est possible de créer un autre compte sur github à des fins personnelles seulement, à votre convenance.

**Comment by etienneleba** [comment]
Bon d'accord c'est dommage alors. Pourriez-vous me partager les sources, inspirations qui vous ont permis de penser cette idée, et en général, qui vous permettent de penser autour des systèmes de décision ?

**Comment by etienneleba** [comment]
D'accord, j'espère que ma question n'a pas été vu comme une reproche car ce n'était absolument pas le but recherché. C'est juste que tout idée est forgé par des inspirations, et ce qui m'intéresse vraiment ce n'est pas l'idée en elle même, mais quelle a été votre chemin de penser pour en arriver à cette idée. C'est pour ça que j'aurais préféré pouvoir situé l'auteur pour comprendre quelles ont été ses expériences et inspirations qui l'ont amené à vouloir repenser un nouveau gouvernement. Mais soit, vous voulez garder votre anonymat, il n'y a pas de problème. 

Je vous partage mes inspirations et sources qui me permettent de penser autour de la démocratie participative et délibérative : 
- Le Rojava, qui est une expérience au nord de la Syrie, une sorte de fédéralisme démocratique 
- Les ateliers constituants
- La démocratie liquide 
- L'identité décentralisée
- [Loomio](https://www.loomio.org/?locale=fr) : une application pour collaborer au sein des entreprises
- les scop en général 
- Les logiciels libre et l'open source, la mentalité hacker
- Le tirage au sort
- La démocratie athénienne
- L'application [decidim](https://decidim.org/) qui permet de la collaboration citoyenne, et en France open source politics qui met en place cette application dans les collectivités locales
- Système de toile de confiance
- Reinventing organizations de Frédéric Laloux
- Les différents types de scrutin (Condorcet randomisé, jugement majoritaire par exemple)
- [La démocratie sous l'angle de la théorie des jeux](https://www.youtube.com/playlist?list=PLtzmb84AoqRSmv5o-eFNb3i9z64IuOjdX) de la chaine science4All
- [Démocratie](https://youtu.be/RAvW7LIML60) de Data gueule 
- La chaine [Politikon](https://www.youtube.com/channel/UC0HxyEc_ojRJ1oJXS5K6oaA) qui parle assez souvent de démocratie
- La chaine [Thinkerview](https://www.youtube.com/user/thinkerview) qui évoque de nombreux sujets
- Les assemblés des assemblés des gilets jaunes, en réunissant des représentants de partout en France, ils ont réussit à créer des assemblés délibératives qui traiter de sujet plutôt complexe comme la création monétaire ou l'urgence climatique. Une sorte d'autoformation à travers la délibération. 
- Les écoles démocratiques 

Je pense avoir fait le tour, dites moi ce que vous en pensait et si des inspirations/sources vous reviennent, n'hésitez pas à m'en faire part 😉

**Comment by etienneleba** [comment]
> 
> Par ailleurs vous pouvez aussi présenter votre intérêt dans les enjeux monétaires et démocratiques que vous avez depuis quelques années, ce serait un autre sujet de discussion "avec l'auteur", n'est-ce pas ?

Oui bien sûr. Je me suis tout abord intéressé à la question de "Qui crée l'argent ?" qui est une question plutôt simple mais dont la réponse n'est pas si simple. Je ne pourrais d'ailleurs toujours pas donner de réponse clair et sûr à 100% même maintenant. Ensuite, j'ai imaginé un outil pour permettre de la démocratie délibérative à grande échelle. Cette outil s'inspire des ateliers constituants et du tirage au sort de représentant et permet en théorie de débattre avec une grande population tout en restant efficace. Sinon voulant trouver une alternative au système de création monétaire actuelle j'ai imaginé un système à porter locale qui est un mixte de MMT (modern monetary theory), de time banking et de monnaie fondante. J'ai aussi imaginé un système de représentation basé sur le tirage au sort qui ressemble un peu à votre système pour choisir un ministre dans votre gouvernement par les idées. Et enfin la dernière est à un stade très peu évolué, c'est les tests constitutionnelles, la constitution serait constitué de tests, un peu à la manière des tests unitaires dans une application.  

Et du coup comme je vous le disais, je suis en train de poser ses idées sur papier, sur github pour être exacte. Je posterais un lien une fois qu'elles seront rédigés si elles vous intéressent 😃

**Comment by democratie-2-0** [comment]
merci pour vos sources, je vais prendre le temps de les lire pour celles que je ne connaissais pas. Les miennes sont plus "prosaïques" : 
- constatant que d'une part les futurs élus ne font attention aux électeurs qu'à l'approche des élections
- et que les programmes "promis" et professions de foi ne sont que rarement tenus :

j'ai cherché à dissocier le contenu du programme --- qui est en générale ce pour quoi on vote avant de voter pour une personne --- de la personne pour qui on vote. La suite est une simple cascade de conséquences : si on doit voter pour des programmes, on doit sélectionner les candidats de façon indépendante de ces idées. Mais voter une seconde fois pour un candidat pour porter la réalisation d'un programme me semblait trop monolithique et rentrait dans le biais du vendeur de commerce auquel on achète des produits parce qu'il a du bagout et non parce qu'il est efficace. D'où la notion de sélection aléatoire dans une liste de candidats. Et pour être moins monolithique et plus réactif, ne pas traiter forcément un programme dans son ensemble mais leurs constituants atomiques (que j'appelle les idées) qui sont parfois communs à plusieurs candidats/partis. 

La question de la fiscalité et de l'argent est annexe dans mon discours, c'est avant tout revoir le pouvoir législatif à l'aune des nouvelles technologies et puisque le peuple est souverain, qu'il a aujourd'hui les moyens d'exercer sa souverainement sans intermédiaires (les députés, les sénateurs), autant lui rendre son pouvoir en directe. Ce qui au passage permet de mieux séparer le pouvoir législatif du pouvoir exécutif, car actuellement en France, c'est pas vraiment la description qu'en fait Montesquieu...

Pour revenir à l'argent, à mon avis on peut le voir comme deux choses différentes : 
- un substitut au troc, sorte de lubrifiant des échanges : si par exemple j'ai besoin d'acquérir un poulet et que je dispose de pains en échange, mais que la personne qui a des poulets ne demande pas du pain mais de l'huile, je dois trouver une tierce personne qui aurait de l'huile et voudrait bien me l'échanger contre du pain, afin de me permettre au bout du compte de troquer cette huile contre le poulet que je souhaitais acquérir. "L'argent" dans ce contexte simplifie les échanges et n'a pas forcément à être crée, ce peut être un bien naturel comme par exemple les fèves de cacao pour les Incas. Avant la monnaie fiduciaire, les pièces étaient en or, en argent en cuivre et c'était le métal --- naturel lui aussi --- qui faisait office "d'argent" (d'où d'ailleurs l'origine de ce terme dans son sens monétaire). Puis ce furent les banques d'état qui émirent des billets comme un titre de propriété d'une fraction de l'or qu'elles avaient en leur coffre, et même alors sauf dans le cas de la dite "planche à billet" l'argent n'était qu'une contrepartie d'un matériaux naturel et donc non crée par l'homme.

- L'argent peut aussi devenir un pouvoir d'achat, une richesse potentielle. On prendra l'exemple de l'éleveur qui fait croître son troupeau, son cheptel, son "capital" (qui est l'origine du mot utilisé dans son contexte financier). Cultiver ainsi son champ pour nourrir ses bêtes sans rien en faire d'autre que de les élever, accroît le potentiel de l'éleveur à acheter (ou à troquer) des biens de toute nature.  Aujourd'hui on élève moins des animaux pour s'enrichir, que des chiffres représentants un avoir virtuel auprès d'un établissement bancaire. On parlera de la Bourse comme source d'enrichissement, mais la bourse ne stock aucun trésor, c'est juste comme l'argent, une moyen de simplifier les échanges par la mise en relation des vendeurs et des acheteurs. En somme les places boursières aussi volatile soient les cours qu'elles indexent, ne créent pas d'argent, ni de richesse. Toutes les plus-values que je peux y faire sont au détriment de ceux qui auront fait des moins-values souvent décalées dans le temps. 

Qui crée l'argent alors ? Même l'utilisation de la planche à billet, quand un état crée artificiellement des billets, va induire une inflation qui au final compensera cette augmentation d'argent par la perte de valeur de la monnaie (je peux acheter moins de biens avec la même valeur faciale d'un billet).  

En fait, l'argent se crée-t-il seulement ? N'est-ce pas simplement comme sur les marchés boursiers l'impression qu'il se crée parce qu'on ne voit qu'une partie de la richesse qui s'accumule sans voir d'où vient cette richesse (l’appauvrissement d'un grand nombre). Prenons une personne qui possède plus d'argent que la moitié de ses concitoyens. On dira probablement qu'elle est riche. Supposons qu'on fasse disparaître la moitié la plus pauvre de la population (on supprime donc une partie de la richesse de la société), cette personne deviendra alors parmi les plus pauvre. Si donc elle était riche, n'était-ce pas parce qu'il y avait plus pauvre qu'elle ?

**Comment by etienneleba** [comment]
Le problème c'est que tout le monde à sa manière de décrire l'argent. Il y a des tonnes de vidéos et d'articles sur le sujet décrivant une façon de théoriser la monnaie. 
Moi je ne veux pas un schéma de comment ça marche, qui la plupart du temps n'est pas sourcé, mais je veux savoir qui à le pouvoir de créer l'argent exactement.
On comprend tous que dans une économie où les échanges se font en fève de cacao, la personne qui produit des fèves de cacao a un certain avantage. 
Plus concrètement, je veux savoir, par exemple, qui appuie sur le bouton lorsque la BCE rachète de la dette à des banques privés lors des politiques de quantitative easing, lorsque ce bouton est appuyer que ce passe-t-il dans l'application, quelle est la structure de la base de donnée qui stock cette action, quels sont les protocoles utilisés, quelles sont les réglementations et qui a décidé que ça se passerait comme ça. 
Je veux un plan exact de comment ça fonctionne, c'est trop important pour être laisser dans les mains d'un petit groupe de personne. 
On pourrait en parler pendant des heures mais je préférais parler de votre système de prise de décision, je suis là pour ça quand même 😅

**Comment by democratie-2-0** [comment]
oui, certes

**Comment by etienneleba** [comment]
Du coup j'ai une question, quelle serait votre stratégie pour mettre en place un tel système ? Je suppose, vu la critique du système actuelle, que vous n'envisageait pas de passer par le système électoral actuelle ? Peut-être envisager de l'implémenter à une échelle locale dans un premier temps ? 

Sinon je ne sais pas si vous l'avez vu passer, mais quelqu'un a publié un article sur cette idée dans le blog de mediapart : https://blogs.mediapart.fr/edrusb/blog/230420/une-democratie-20

**Comment by democratie-2-0** [comment]
La mise en place d'un tel système passe d'abord par sa diffusion, son amélioration, de débats éventuels sur des options et des améliorations pour arriver à un consensus. Mon objectif est là, car c'est ce que j'aimerais avoir comme système exécutif aujourd'hui en France. Pour le mettre en place, je ne peux le faire seul, il faut déjà ce consensus sur ce qu'on veut mettre en place avec une majorité de citoyens qui le réclament. 

Si on en arrive là alors, la question se posera effectivement de savoir comment le mettre en place, mais ça me semble tellement loin et j'ai par ailleurs tant de mal à faire connaître cette proposition que c'est une question à laquelle je ne peux répondre aujourd'hui et pour laquelle je n'aurai fort probablement pas mon mot à dire. 

Une mise en place à une échelle locale est effectivement une chemin qui semble plus accessible, mais quand les échelles locales (communes, aglo, département, régions, etc.) sont régies par des lois nationales, ça ne change pas le problème.

Enfin, c'est déjà bien s'il y a une référence à ce travail dans Mediapart. Est-ce ainsi que vous l'avez trouvé ? Le problème avec github c'est qu'il n'y a pas d'outil de mesure de l'audience donc je ne sais pas du tout si je suis lu, ni par qui...
Si vous avez des suggestions pour diffuser plus largement cet travail, n'hésitez pas à m'en faire part.

**Comment by etienneleba** [comment]
Oui d'accord.

Non, je l'ai trouvé par github mais en passant par google pour le retrouver, je suis tomber sur l'article de blog sur medipart.

J'aurais plusieurs suggestions à vous faire pour une diffusion plus large et un approfondissement  de l'idée.

Il faudrait que vous définissez bien plus explicitement les problèmes auxquels vous vous attaquez. A part l'introduction de 3 lignes et quelques fois dans l'exposé, vous ne définissez pas, clairement, les problèmes. Pour la majorité des personnes, le gouvernement représentatif actuel est la meilleur façon de prendre des décisions. Il faut que vous expliquiez, clairement, ce que sont les dérives de l’élection, de la représentation, la différence entre les conflits d'idée et de personne etc. Et si vous le pouvez, avec des sources ou des exemples historiques. Si les personnes ne comprennent pas quels problèmes votre solution résout, alors ils ne prendront même pas la peine de lire votre solution. 

Ensuite, je pense que vous devriez détacher l'idée abstraite, de l'implémentation qui pour vous serez idéal. 
Je m'explique sur les termes d'idée abstraite et d'implémentation.
Pour l'idée abstraite, c'est le fond de l'idée, la base solide. Une sorte de définition clair. Par exemple, pour un gouvernement représentatif la définition abstraite d'après wikipédia serait : La démocratie représentative, le gouvernement représentatif ou le régime représentatif est un système politique dans lequel on reconnaît à une assemblée restreinte le droit de représenter un peuple, une nation ou une communauté. La volonté des citoyens s’exprime à travers des représentants qui établissent les lois (pouvoir législatif) et les font appliquer (pouvoir exécutif).
Aucune localité ou échelle n'est défini ça permet de penser de nombreuse formes d'implémentation à différents échelle. 
Par exemple, la France, l’Angleterre, les États-Unis implémentent des gouvernements représentatif de différentes façons.    
De plus, en séparant l'idée abstraite, des implémentations ça permet que les critiques d'une implémentation n'affectent pas l'idée de fond. Et même, au lieu de débattre sur des détails d'implémentation, les personnes qui critiquent votre implémentation ont la possibilité de proposer leur propre implémentation. Ça permet de transformer des critiques en contribution. 

Après ces différents étapes vous allez vous retrouvez avec beaucoup de contenu, votre idée sera certes bien plus forte mais complémentent illisible pour quelqu'un qui veut juste la découvrir. Vous devez vulgariser les problèmes et l'idée abstraite. Une à deux phrases pour résumer les problèmes et une dizaine de ligne pour l'idée abstraite. Se résumer vous permettra de diffuser votre idée beaucoup plus facilement. Un lien vers les détails de l'idée permettra aux personnes intéressés de s'y plonger plus longuement et pourquoi pas de proposer une implémentation. 

C'est ma méthode pour décrire une idée, je ne dis pas que c'est la méthode ultime, mais je pense que ça permet d'avoir une bonne base pour réfléchir sur une idée.

Sinon sur la forme, vous devriez faire de petites modifications sur votre site. Un bloc texte centré, une police comme Helvetica ou open sans devraient rendre le site un peu plus facile à lire. 

Voilà mes petites suggestions 😄

**Comment by democratie-2-0** [comment]
Bonjour, vos remarques sont très pertinentes, merci ! 
Pour les derniers points, (bloc centré, police) les changements sont maintenant effectués.

Bon, il me reste à trouver le temps de faire ça, et merci d'avoir ravivé ma motivation sur ce projet  :+1:

**Comment by etienneleba** [comment]
Pour le style de votre site vos modifications sont déjà bien, si vous voulez, voici un style très simple qui je pense rendra mieux. Etant développeur web je me sens obligé d'apporter ma petite touche sur ce sujet mais soyez libre de l'utiliser ou non :smile: 
```
html {
    font-family: 'Open Sans', Arial, sans-serif;
    text-align: justify;
    color: #1a1a1a;
    margin: 2%;
}
body {
   max-width: 980px;
   margin: auto;
}
h1, h2, h3, h4, h5 {
  color: #1a1a1a;
}

a {
    color: DarkBlue;
}

```
En bonus, une balise meta à mettre dans le head de l'HTML pour rendre le site lisible plus facilement sur mobile. 

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

J'ai hâte de vous lire, ça fait vraiment plaisir de voir que d'autres personnes s'intéressent à ce sujet. Je vais de mon côté avancer sur la rédaction de mes idées. Bonne continuation, n'hésitez pas si vous avez besoin de relecture ou pour mettre en forme votre site web :wink:

**Comment by democratie-2-0** [comment]
merci pour ces compléments techniques ! 
N'hésitez pas à me faire part de vos écrits de la même manière :)

**Comment by democratie-2-0** [comment]
Bonjour,

voilà, j'ai suivi vos conseils. Une introduction qui j'espère donne envie d'aller lire le projet, une liste des problèmatiques et une abstraction du GPI pour appliquer ce principe à d'autres échelons.

Je dois encore relire car il se peut que j'ai encore laissé traîner que fautes d'orthographe...

**Comment by democratie-2-0** [comment]
ne pas hésiter à rouvrir la discussion, si nécessaire
